### ISSUE TITLE
Attributes not escaped correctly

### ISSUE THREAD

**Issue by madleech** [ioquatix/trenni#1]
Hi, seems like xml attributes aren't being escaped properly?

**Using Trenni:**

``` ruby
attr = '1&2"3<4'
xml = Trenni::Builder.fragment { |b| b.tag 'test', 'attr' => attr }.to_s
# => "<test attr=\"1&2\"3<4\"/>"
expect(Nokogiri::XML(xml).at_css('test').attr('attr').to be == attr # fails
```

Ideally the attribute values should be escaped, as Nokogiri does for the following:

**Using Nokogiri:**

``` ruby
doc = Nokogiri::XML(xml)
doc.at_css('test')['attr'] = attr
doc.to_s
# => "<?xml version=\"1.0\"?>\n<test attr=\"1&amp;2&quot;3&lt;4\"/>\n"
```

**Comment by ioquatix** [comment]
By default `Trenni::Builder` doesn't escape attributes. This might seem like a bug but its a deliberate design as sometimes you are using `Builder` to process already escaped text. By default, Trenni assumes you know what you are doing and doesn't apply the overhead of escaping incoming attributes.

However, this is an option you can turn on:

``` ruby
attr = '1&2"3<4'
xml = Trenni::Builder.new(escape: true).tap{|b| b.tag 'test', 'attr' => attr }.output.to_s
=> "<test attr=\"1&amp;2&quot;3&lt;4\"/>"
```

Obviously there are performance implications, and you need to make sure anything you are processing is not already escaped, etc.

**Comment by madleech** [comment]
Ok great, thank you.

**Comment by ioquatix** [comment]
God damn it I'm an idiot
